pipeline {
    agent any

    stages {
        stage('Build DOM image') {
            steps {
                sh 'chmod +x ./server/jenkins/scripts/build.sh'
                sh './server/jenkins/scripts/build.sh'
            }
        }
    }
}